### PR TITLE
Atv3 23/09

### PR DESCRIPTION
**Pull request by gabrielbrandaodelima**
This branch was created on head of previous activity branch. 

SO this activity has all implementations of activity from 18/09 -> PR #94

Finished implementation

### CODE REVIEW

**Comment by gabrielbrandaodelima** [comment]
image

**Comment by gabrielbrandaodelima** [comment]
image
image

**Comment by gabrielbrandaodelima** [comment]
Some test prints above ☝️ 

My display is tiny because I'm using Ubuntu in VIrtual box , so the last print is a little cropped

**Comment by romildo** [comment]
Muito bom.

**Pull request closed without merging**
